### ISSUE TITLE
[bug] Some text (track/folder names etc) is capped off a bit on the last character

### ISSUE THREAD

**Issue by TheDalaiAlpaca** [omega-gg/MotionBox#9] opened 2018-09-25 19:43 UTC
See screenshot. It's a very minor thing, but still reporting because why not.

![motionbox](https://user-images.githubusercontent.com/29703645/46038233-0ac77180-c0fa-11e8-9324-ead6b4f227c7.png)

Ubuntu 18.04.1 LTS
Motionbox 1.4.0-7
VLC 3.0.3
Linux 4.15.0-34-generic
OS type: 64bit
Screen resolution: 1920x1080

Doesn't occur on Windows (for me at least)

**Comment by 3unjee** [comment] 2018-09-29 09:29
@TheDalaiAlpaca, can't seem to be able to reproduce that on my side. Are you sure you have Arial on your system ?

**Comment by TheDalaiAlpaca** [comment] 2018-11-22 16:20
You are right. Turns out Ubuntu doesn't have the Arial font (it's proprietary). I installed it and the font changed in Motionbox.

**Comment by 3unjee** [comment] 2019-07-20 08:48
This should be fixed in the latest version since I rolled back to Qt standard Text component.

**Closed by 3unjee** 2019-07-20 08:48 UTC
